version: '3'
services:

  db:
    image: postgres:11
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: {{cookiecutter.artifact_id}}

    ports:
      - "5432:5432"
