server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application.name: {{cookiecutter.artifact_id}}

  datasource:
    url: jdbc:postgresql://localhost:5432/{{cookiecutter.artifact_id}}
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect